# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeedPet' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for FeedPet
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    
    pod 'GoogleSignIn'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    
    
    pod 'SwiftyJSON'
    pod 'XLPagerTabStrip', '~> 8.0'
    pod 'ChartProgressBar', '~> 1.0'
    
end

